apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fbctest
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/scoheb/user-workload@sha256:242c01f4dfd86410d2499cf53f13d25c52c3f98f73e1fd1387784cd3e66f4f32
        name: container-image
        resources: {}
status: {}
